eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: accountsModule
          uri: lb://ACCOUNTS
          predicates:
          - Path=/accounts/**